# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb105e8226fd6fddbd3fb296c81ed6a7eeaae171b3e417d609e5acdc07272e7f21d5d15bda8bb3182802edc594db8f0d56a22a347415662571a4419147b63914
  coin_btc_wallet_key: 'http://test1st:1sttest@127.0.0.1:9300'
  coin_ltc_wallet_key: 'http://test1st:1sttest@127.0.0.1:9301'
  coin_mona_wallet_key: <%= ENV["COIN_MONA_WALLET_KEY"] %>
  coin_doge_wallet_key: 'http://test1st:1sttest@127.0.0.1:9303'
  smtp_username: 'webtestsrvs@gmail.com'
  smtp_password: 'testdake'

test:
  secret_key_base: 2f1e9dc2c79346c9c4dd356072e8958da40dc527da955c43865998d8df039779cdbac23cef27751f03bc204493a485c9eca60956b209583d29f622ab8e0212e6
  coin_btc_wallet_key: 'http://test1st:1sttest@127.0.0.1:9300'
  coin_ltc_wallet_key: 'http://test1st:1sttest@127.0.0.1:9301'
  coin_mona_wallet_key: 'http://test1st:1sttest@127.0.0.1:9302'
  coin_doge_wallet_key: 'http://test1st:1sttest@127.0.0.1:9303'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  coin_btc_wallet_key: <%= ENV["COIN_BTC_WALLET_KEY"] %>
  coin_ltc_wallet_key: <%= ENV["COIN_LTC_WALLET_KEY"] %>
  coin_mona_wallet_key: <%= ENV["COIN_MONA_WALLET_KEY"] %>
  coin_doge_wallet_key: <%= ENV["COIN_DOGE_WALLET_KEY"] %>
