# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  coin_btc_wallet_key: <%= ENV["COIN_BTC_WALLET_KEY"] %>
  coin_ltc_wallet_key: <%= ENV["COIN_LTC_WALLET_KEY"] %>
  coin_mona_wallet_key: <%= ENV["COIN_MONA_WALLET_KEY"] %>
  coin_doge_wallet_key: <%= ENV["COIN_DOGE_WALLET_KEY"] %>
  coin_btc_passphrase: <%= ENV["COIN_BTC_PASSPHRASE"] %>
  coin_ltc_passphrase: <%= ENV["COIN_LTC_PASSPHRASE"] %>
  coin_mona_passphrase: <%= ENV["COIN_MONA_PASSPHRASE"] %>
  coin_doge_passphrase: <%= ENV["COIN_DOGE_PASSPHRASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  coin_btc_wallet_key: <%= ENV["COIN_BTC_WALLET_KEY"] %>
  coin_ltc_wallet_key: <%= ENV["COIN_LTC_WALLET_KEY"] %>
  coin_mona_wallet_key: <%= ENV["COIN_MONA_WALLET_KEY"] %>
  coin_doge_wallet_key: <%= ENV["COIN_DOGE_WALLET_KEY"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  coin_btc_wallet_key: <%= ENV["COIN_BTC_WALLET_KEY"] %>
  coin_ltc_wallet_key: <%= ENV["COIN_LTC_WALLET_KEY"] %>
  coin_mona_wallet_key: <%= ENV["COIN_MONA_WALLET_KEY"] %>
  coin_doge_wallet_key: <%= ENV["COIN_DOGE_WALLET_KEY"] %>
  coin_btc_passphrase: <%= ENV["COIN_BTC_PASSPHRASE"] %>
  coin_ltc_passphrase: <%= ENV["COIN_LTC_PASSPHRASE"] %>
  coin_mona_passphrase: <%= ENV["COIN_MONA_PASSPHRASE"] %>
  coin_doge_passphrase: <%= ENV["COIN_DOGE_PASSPHRASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
